package version

import (
	"errors"
	"fmt"
	"html/template"
	"io/ioutil"
	"os"
	"strconv"
	"strings"
)

const (
	tmpl = `package {{ .PackageName }}

// WARNING: Auto generated version file. Do not edit this file by hand.
// WARNING: go get github.com/sabhiram/gover to manage this file.
// Version: {{ .Major }}.{{ .Minor }}.{{ .Patch }}

const (
	Major = {{ .Major }}
	Minor = {{ .Minor }}
	Patch = {{ .Patch }}

	Version = "{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
)
`
	versionKey = "// Version: "
	packageKey = "package "
)

////////////////////////////////////////////////////////////////////////////////

type Version struct {
	PackageName string
	Major       uint64
	Minor       uint64
	Patch       uint64
}

////////////////////////////////////////////////////////////////////////////////

func (v *Version) unmarshalSemVer(s string) error {
	var err error

	items := strings.Split(s, ".")
	if len(items) < 3 {
		return fmt.Errorf("%s is an invalid version", s)
	}

	v.Major, err = strconv.ParseUint(items[0], 10, 64)
	if err != nil {
		return err
	}

	v.Minor, err = strconv.ParseUint(items[1], 10, 64)
	if err != nil {
		return err
	}

	v.Patch, err = strconv.ParseUint(items[2], 10, 64)
	return err
}

func (v *Version) incrMajor() {
	v.Major += 1
	v.Minor = 0
	v.Patch = 0
}

func (v *Version) incrMinor() {
	v.Minor += 1
	v.Patch = 0
}

func (v *Version) incrPatch() {
	v.Patch += 1
}

func (v *Version) update() error {
	t, err := template.New("gover").Parse(tmpl)
	if err != nil {
		return err
	}

	f, err := os.Create("version_gen.go")
	if err != nil {
		return err
	}
	defer f.Close()

	return t.Execute(f, v)
}

func (v *Version) String() string {
	if v == nil {
		return ""
	}
	return fmt.Sprintf("%d.%d.%d", v.Major, v.Minor, v.Patch)
}

////////////////////////////////////////////////////////////////////////////////

func Init(vs, pn string) error {
	v := &Version{}
	if err := v.unmarshalSemVer(vs); err != nil {
		return err
	}
	v.PackageName = pn

	return v.update()
}

func Load() (*Version, error) {
	bs, err := ioutil.ReadFile("version_gen.go")
	if err != nil {
		return nil, err
	}

	fc := string(bs)
	v := &Version{
		PackageName: "main",
	}

	if idx := strings.Index(fc, packageKey); idx >= 0 {
		pkg := fc[idx+len(packageKey):]
		if idx = strings.Index(pkg, "\n"); idx >= 0 {
			pkg = pkg[:idx]
		}
		v.PackageName = pkg
	}

	if idx := strings.Index(fc, versionKey); idx >= 0 {
		ver := fc[idx+len(versionKey):]
		if idx = strings.Index(ver, "\n"); idx >= 0 {
			ver = ver[:idx]
		}
		return v, v.unmarshalSemVer(ver)
	}

	return nil, errors.New("version not found in gen file")
}

func Increment(op string) error {
	v, err := Load()
	if err != nil {
		return err
	}

	switch op {
	case "major":
		v.incrMajor()
		fmt.Printf("Major incremented.\n")
	case "minor":
		v.incrMinor()
		fmt.Printf("Minor incremented.\n")
	case "patch":
		v.incrPatch()
		fmt.Printf("Patch incremented.\n")
	default:
		return fmt.Errorf("cannot increment %s", op)
	}

	return v.update()
}
