language: go

go:
  - "1.10"
  - tip

env:
  - "PATH=$HOME/gopath/bin:$PATH"

before_install:
  - go get github.com/mitchellh/gox

script:
  - go test -v ./...
  - gox -os="linux darwin windows" -arch="amd64" -output="bin/{{.Dir}}_{{.OS}}_{{.Arch}}" -verbose ./...

deploy:
  provider: releases
  api_key:
    secure: YepcIVZXZ07prrixF9lpgGRLdvDfxzytf0WwtpjfoAFCCeGnlZz4y1w3ICLiggOe3rvjTUNWB+KI3kQzlDBGwAhsKOYt8yYWD8B2jyYYCnNE5b9zT6R6OeezrjVZL7fBE6A5QgvThwB83YfgvqFEQHh+tk5COUG2e/2bGT6R7jwtSSqA9CMzKJ3DbctyN6uQb/ZcsgcYxypQ6Nnv9KB1uggY+YeylA+JZkllCK3LiWihKsgCWmu3A3FmRgOAvXXY8M5+FQDhz0Vpl6djujYj3ruztgx4qHeojenXDoImPuQjHZ541vYjNpiOGcmH+halJFHH7bxAJcg2v0ZrYdIkmkW9lz3ZxlHdaswNrk8epDe1l8DO4c6y50Rwn3HfBRB7gn+rv2jXd6bzqLTn6tHvogEXo6IpDrSxYhIJPTdx9Y+F9wRPfjdlisDcDCFvnoPNhTf9lwqsRKqSBv/MXp43wkNQ4B1u+lrV5KiA1Yky9gUPLX4Z8WTmH0aEkyyC/larreidkcZXnXpJhWryfZ7qzMgEo4yuQ4rrocPN90PXKV7E+UfDZWUnT8tboGMoBFgIrpZwI6knrPv3zdV3WfN51QqgGx5FnigCBz/P/wEE+FgHLQgETXxhn2S14kHc6jjYbpNXW/k7PvWSlTPiEHQOjwDeujOHplvh3iSLp34ceQ8=
  file:
    - bin/gover_darwin_amd64
    - bin/gover_linux_amd64
    - bin/gover_windows_amd64.exe
  skip_cleanup: true
  on:
    repo: sabhiram/gover
    tags: true
